replicaCount: 1

image:
  repository: riko-inc/task-service
  tag: latest
  pullPolicy: Never

service:
  port: 8080

ingress:
  enabled: true

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"