replicaCount: 1

image:
  repository: your-docker-registry/task-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

ingress:
  enabled: true
  annotations: {}
  host: "task-service.local"
