apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-headless
  namespace: "services"
spec:
  clusterIP: None
  ports:
    - port: 9093
      name: controller
    - port: 9092
      name: client
  selector:
    app: {{ .Chart.Name }}