apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: services
spec:
  type: ClusterIP
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
    - name: external
      port: 29092
      targetPort: 29092
    - name: controller
      port: 9093
      targetPort: 9093
    - name: metrics
      port: 9404
      targetPort: 9404
  selector:
    app: kafka