apiVersion: v1
kind: Service
metadata:
  name: {{"{{ include \"kafka.fullname\" . }}"}}
  labels:
    {{"{{ include \"kafka.labels\" . | nindent 4 }}"}}
spec:
  type: {{"{{ .Values.kafka.service.type }}"}}
  ports:
    - name: internal
      port: {{"{{ .Values.kafka.service.internalPort }}"}}
      targetPort: internal
    - name: external
      port: {{"{{ .Values.kafka.service.external.port }}"}}
      targetPort: external
      {{"{{- if .Values.kafka.service.external.enabled }}"}}
      loadBalancer: {}
      {{"{{- end }}"}}
    - name: metrics
      port: {{"{{ .Values.kafka.service.metricsPort }}"}}
      targetPort: metrics
  selector:
    {{"{{ include \"kafka.selectorLabels\" . | nindent 4 }}"}}