apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels: {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "kafka.selectorLabels" . | nindent 4 }}
  ports:
    - name: external
      port: {{ .Values.service.ports.external }}
      targetPort: external
    - name: controller
      port: {{ .Values.service.ports.controller }}
      targetPort: controller