apiVersion: v1
kind: Service
metadata:
  name: "kafka"
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
    - name: internal
      port: {{ .Values.kafka.service.internalPort }}
      targetPort: internal
    - name: external
      port: {{ .Values.kafka.service.external.port }}
      targetPort: external
    - name: metrics
      port: {{ .Values.kafka.service.metricsPort }}
      targetPort: metrics
  selector:
    app: "kafka"