apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "file-service.name" . }}-ingress
  namespace: services
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /file/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "file-service.name" . }}
                port:
                  number: 8080
