apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "task-service.fullname" . }}
  labels:
    app: {{ include "task-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "task-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "task-service.name" . }}
    spec:
      containers:
        - name: {{ include "task-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: redis-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
