apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-service-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: "82.202.138.236"
      http:
        paths:
          - path: /task-service
            pathType: Prefix
            backend:
              service:
                name: task-service
                port:
                  number: 8080
