replicaCount: 1
namespace: services

image:
  repository: riko-inc/auth-service
  tag: latest
  pullPolicy: Never

service:
  port: 8080
  schema: auth_service
  swagger-config-url: "/v3/api-docs/swagger-config"

ingress:
  enabled: true
  host: ""

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"