apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: {{ include "postgres.fullname" . }}
  DB_PORT: "{{ .Values.port }}"
  DB_NAME: {{ .Values.database }}
  DB_USER: {{ .Values.user }}
  DB_PASSWORD: {{ .Values.password }}