apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.image }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.service.database }}
            - name: POSTGRES_USER
              value: {{ .Values.service.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.service.password }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "400m"