apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}