controller:
  service:
    type: NodePort
    nodePorts:
      http: 80
      https: 443
    externalTrafficPolicy: Local
  hostNetwork: true
  ingressClassResource:
    name: nginx
    enabled: true
    default: true