controller:
  service:
    type: NodePort
    nodePorts:
      http: 31064
      https: 31065
    externalTrafficPolicy: Local
  hostNetwork: true
  ingressClassResource:
    name: nginx
    enabled: true
    default: true