apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}-config
  namespace: {{ .Values.namespace }}
data:
  SERVICE_PORT: "{{ .Values.service.port }}"
  SERVICE_NAME: {{ .Values.service.shortname }}-service
  DEFAULT_SCHEMA: {{ .Values.service.shortname }}_service
  SERVICE_SHORTNAME: {{ .Values.service.shortname }}
  SWAGGER_PREFIX: "/{{ .Values.service.shortname }}"
  AUTH_SERVICE_HOST: "http://auth-service:8080"
  TASK_SERVICE_HOST: "http://task-service:8080"
  SPACE_SERVICE_HOST: "http://space-service:8080"
  PORT: "8080"