apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ml-service.name" . }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /ml/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "ml-service.name" . }}
                port:
                  number: 8080
