apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-service.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "ml-service.name" . }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ include "ml-service.name" . }}
