kafka:
  image:
    repository: bitnami/kafka
    tag: "3.8"
    pullPolicy: IfNotPresent
  nodeId: "0"
  clusterId: "abcdefghijklmnopqrstuv"
  processRoles: "controller,broker"
  controllerQuorumVoters: "0@kafka:9093"
  superUsers: "User:sa"
  listenerSecurityProtocolMap: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
  controllerListenerNames: "CONTROLLER"
  interBrokerListenerName: "INTERNAL"
  service:
    type: ClusterIP
    internalPort: 9092
    external:
      enabled: true
      type: LoadBalancer
      port: 29092
    metricsPort: 9404
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 10
    failureThreshold: 3
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 10
    failureThreshold: 3