name: Update configuration

on:
  push:
    branches: [ develop ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make git pull on server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/user1
            git stash
            git pull origin develop
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            helm upgrade --install global-config ./global-config -n services
          debug: true
